### ISSUE TITLE
Deferred.Or_error.try_with or Monitor.try_with_or_error

### ISSUE THREAD

**Issue by brendanlong** [janestreet/async_kernel#14]
Is it possible to get some guidance on the difference between these two functions and if one is preferred over the other?

They seem to have similar code, but they're not aliases:

https://github.com/janestreet/async_kernel/blob/master/src/monitor.ml#L430
https://github.com/janestreet/async_kernel/blob/master/src/deferred_or_error.ml#L86

Does Jane Street use one or both of these, and if there's cases where you use one and not the other, what's the reason?

**Comment by seliopou** [comment]
Yeah they look pretty much the same. Oddly the `Deferred_or_error` version gives you control over whether `f` is called synchronously or scheduled in a job, while the one in `Monitor` will always call `f` synchronously.

It looks like we use `Deferred.Or_error.try_with` more frequently, but my guess would be that it's just more discoverable than than `Monitor.try_with_or_error`.

**Comment by brendanlong** [comment]
I guess that makes sense, if `Deferred.Or_error.try_with` is more discoverable and also has additional features.

**Comment by seliopou** [comment]
Closing, unless further discussion is needed.
