### ISSUE TITLE
waiting for a Deferred...

### ISSUE THREAD

**Issue by progman1** [janestreet/async_kernel#15]
hello,
is there a way to extract a result from a deferred?
ie.
```
val await: 'a Deferred.t -> 'a
```
while this synchronous behaviour goes against the grain of Async,
I have a piece of code I don't want to bend out of shape to fit into Async.
in particular, this code is already running under the Async lock and I see
this hypthetical function as merely about Async performing cycles until
the offered deferred itself is determined and the function can then return
the desired result. No busy waiting.
I have a strong feeling this is already available in some form but I
have not found it.

**Comment by anuragsoni** [comment]
Async_unix has some functions that will help you with this block_on_async/block_on_async_exn/run_in_async_wait/run_in_async_wait_exn https://github.com/janestreet/async_unix/blob/0d543cff294f09048513899cd773847709be0e16/src/thread_safe.mli#L56-L76

**Comment by seliopou** [comment]
`block_on_async` will do this, but it's worth reading its implementation so you understand precisely under which circumstances it is safe to use it.
