### ISSUE TITLE
Pipe.transfer documentation does not reflect its implementation

### ISSUE THREAD

**Issue by seliopou** [janestreet/async_kernel#3]
The documentation of `Pipe.transfer` states that

> [transfer] is a specialization of [transfer'] that uses [Queue.map ~f]

implying that it will perform batch reads and writes. However the implementation reads elements from the `Pipe.t` one element at a time, as indicated by the use of `read_now`, rather than `read_now'`:

```ocaml
let transfer input output ~f =
  transfer_gen read_now write input output ~f:(fun a k -> k (f a))
;;
```
Which one is the indented behavior: the documented behavior or the actual behavior?

**Comment by bmillwood** [comment]
The comment now says

> [transfer] is like [transfer'], except that it processes one element at time.
