### ISSUE TITLE
Add an optional size_budget parameter to Pipe.create

### ISSUE THREAD

**Issue by philtomson** [janestreet/async_kernel#4]
Instead of having to call Pipe.set_size_budget after the creation of a Pipe, why not add an optional size_budget parameter to Pipe.create to set the size_budget field of the Pipe.t? This would help document the fact that the default size is 0 and it would eliminate the need to set the size separately.

(not saying that set_size_budget should be eliminated as it could be handy to be able to change the size_budget later)

**Comment by xclerc** [comment]
Fixed by https://github.com/janestreet/async_kernel/commit/fbd3c3dc024398b5a991b880f76b93560d881061.
