### ISSUE TITLE
Async_kernel.Debug module still has a Unix dependency

### ISSUE THREAD

**Issue by avsm** [janestreet/async_kernel#6]
Due to logging the PID.  Spotted by @hhugo in mirage/ocaml-cohttp#279

**Comment by diml** [comment]
This will be fixed in the next release.

**Comment by trevorsummerssmith** [comment]
Is there an expected date for the next release? Thanks.

**Comment by bmillwood** [comment]
This is now fixed. The get-my-PID function is now in a ref that defaults to something non-unixy, and async_unix fills it in as appropriate.
